# Generated by Django 4.2.2 on 2023-06-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_description_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
