# Generated by Django 4.2.2 on 2023-06-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_details_total_price_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_details',
            new_name='OrderDetails',
        ),
    ]
